version: "3"
services:
  datadog-agent:
    image: "gcr.io/datadoghq/agent:latest"
    container_name: datadog-agent
    env_file:
      - DD_API_KEY= #add your DD API Key here
    environment:
      - DD_APM_ENABLED=true
      - DD_LOGS_ENABLED=true 
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      - DD_APM_NON_LOCAL_TRAFFIC=true 
      - DD_ENV=dev
      - DD_LOG_LEVEL=INFO
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
    links: 
      - web
  web:
    build: 
      context: ./app
    container_name: flaskapp
    volumes:
      - ./app/app:/usr/src/app
    environment:
      - DD_AGENT_HOST=datadog-agent
      - DATADOG_TRACE_DEBUG=true
      - DD_ENV=dev
      - DD_SERVICE=python_sandbox_web
      - DD_VERSION=1.0.0

  #Nginx Service
  nginxserver:
    build: 
        context: ./nginx
    container_name: nginxserver
    restart: unless-stopped
    environment:
      - DD_ENV=dev
      - DD_SERVICE=nginx_sandbox
      - DD_AGENT_HOST=datadog-agent
      - DD_VERSION=1.0.0
    tty: true
    ports:
      - "80:80"
      - "443:443"